import type { ProjectItem } from '../types';

export const projectsData: ProjectItem[] = [
  {
    id: 'careerpilot-ai',
    title: 'CareerPilot - AI-Powered Job Portal',
    shortDescription:
      'An AI-powered job portal built with Spring Boot microservices and React.js connecting Job Seekers, Employers, and Administrators with Gemini AI integration and automated candidate workflows.',
    detailedDescription:
      'CareerPilot is an AI-powered job portal developed using Spring Boot microservices architecture and React.js. The platform connects Job Seekers, Employers, and Administrators through a centralized platform, featuring intelligent AI integrations for resume feedback, cover letter generation, candidate screening, and automated job recommendations.',
    technologies: [
      'Java',
      'Spring Boot',
      'React.js',
      'MySQL',
      'Microservices',
      'Google Gemini AI',
      'Spring Cloud Config',
      'Eureka Discovery',
      'API Gateway',
      'JWT Authentication',
      'Razorpay',
    ],
    architecture: 'Spring Boot Microservices & Cloud Infrastructure',
    projectType: 'AI & Microservices Application',
    duration: '1 Month',
    githubUrl: 'https://github.com/AniketSalve2373/CareerPilot',
    featured: true,
    badge: 'AI & Microservices',
    category: 'Full Stack & AI',
    role: 'Full Stack & Microservices Developer',
    keyFeatures: [
      'Six Business Microservices & Centralized API Gateway',
      'Spring Cloud Config Server & Eureka Service Discovery',
      'JWT Authentication & Role-Based Access Control (RBAC)',
      'Google Gemini AI Integration for Resume Feedback & Cover Letter Generation',
      'AI-Powered Candidate Screening & Automated Job Recommendations',
      'End-to-End Job Management, Resume Uploads, & Application Tracking',
      'Real-Time Notifications & Razorpay Premium Subscriptions',
    ],
    highlights: [
      'Architected 6 decoupled business microservices registered under Eureka Discovery with an API Gateway entry point.',
      'Embedded Google Gemini AI API for generating automated resume feedback and customized cover letters.',
      'Implemented secure JWT-based RBAC for Job Seekers, Employers, and Admins alongside Razorpay payment processing.',
    ],
  },
  {
    id: 'careerpilot-dotnet',
    title: 'CareerPilot - .NET Job Portal',
    shortDescription:
      'A full-stack, role-based job recruitment platform engineered with ASP.NET Core 8 Clean Architecture, React.js, EF Core, and MySQL for seamless employer-applicant workflows.',
    detailedDescription:
      'CareerPilot .NET is a full-stack, role-based job portal connecting Job Seekers, Employers, and Administrators through a centralized platform. Engineered adhering to Clean Architecture principles, Repository Pattern, and Unit of Work, it provides robust job lifecycle management, PDF resume management, and admin approvals.',
    technologies: [
      'C#',
      'ASP.NET Core 8',
      'React.js',
      'MySQL',
      'Entity Framework Core',
      'Clean Architecture',
      'JWT',
    ],
    architecture: 'Clean Architecture, Repository & Unit of Work Pattern',
    projectType: '.NET Enterprise Web Application',
    duration: '1 Month',
    // githubUrl intentionally omitted / undefined - do NOT invent a URL
    featured: true,
    badge: 'Clean Architecture',
    category: '.NET Enterprise',
    role: '.NET Full Stack Developer',
    keyFeatures: [
      'Clean Architecture, Repository Pattern, & Unit of Work Pattern',
      'JWT Authentication with Access & Refresh Tokens',
      'Role-Based Authorization (Job Seekers, Employers, Admins)',
      'Employer Registration Workflow & Admin Approval Pipeline',
      'Job Lifecycle Management, Multi-Filter Search, & Pagination',
      'Job Seeker Profile & PDF Resume Upload / Download / Delete',
      'Job Applications, Application Tracking, & Bookmarking',
      'Role-Specific Dashboards & Dedicated Admin Dashboard',
    ],
    highlights: [
      'Structured application layer using ASP.NET Core 8 Clean Architecture to decouple domain models, repositories, and UI.',
      'Integrated EF Core with MySQL for transaction safety via Unit of Work and efficient LINQ query generation.',
      'Built interactive React frontend supporting full PDF resume management, bookmarking, and paginated job filtering.',
    ],
  },
  {
    id: 'smart-task-tracker',
    title: 'Smart Task Tracker',
    shortDescription:
      'A full-stack role-based task management web application built with Spring Boot, ReactJS, and MySQL for task delegation, tracking, and lifecycle administration.',
    detailedDescription:
      'Smart Task Tracker is a full-stack role-based task management application designed to streamline workflows between administrators and employees. It features secure authentication, role-based access control, task delegation, and progress tracking from pending to completion.',
    technologies: [
      'Spring Boot',
      'ReactJS',
      'MySQL',
      'Java',
      'JWT',
      'REST API',
    ],
    architecture: 'Layered Full-Stack Architecture',
    projectType: 'Task Management System',
    duration: '1 Month',
    githubUrl: 'https://github.com/AniketSalve2373/smart-task-tracker',
    featured: false,
    badge: 'Task Management',
    category: 'Full Stack & AI',
    role: 'Full Stack Developer',
    keyFeatures: [
      'Full-Stack Role-Based Task Management System',
      'JWT Authentication & Secure RBAC',
      'Admin & Employee Functionalities',
      'Task Assignment & Workload Allocation',
      'Task Progress Tracking & Lifecycle (Pending to Completed)',
    ],
    highlights: [
      'Developed RESTful APIs in Spring Boot with Spring Security and JWT for granular user access management.',
      'Designed intuitive React user interface for seamless task assignment, status toggling, and employee monitoring.',
      'Modeled relational database schemas in MySQL to manage task assignments, progress logs, and user roles.',
    ],
  },
  {
    id: 'skill-tracker',
    title: 'Skill Tracker',
    shortDescription:
      'A full-stack web application built with React, Node.js, Express, and MongoDB for logging technical proficiencies, tracking progress scores (0-100), and skill auditing.',
    detailedDescription:
      'Skill Tracker is a full-stack web application engineered for tracking individual technical competencies, progress scoring from 0 to 100, and auditing skill growth. Developed with the MERN stack (MongoDB, Express, React, Node) using Routes → Controllers → Models architecture, it includes admin controls, leaderboards, and MongoDB aggregation analytics.',
    technologies: [
      'React.js',
      'Node.js',
      'Express.js',
      'MongoDB',
      'Mongoose',
      'JWT',
      'Bootstrap',
      'Vite',
      'Axios',
    ],
    architecture: 'Routes → Controllers → Models (MERN)',
    projectType: 'Full-Stack Web Application',
    duration: '1 Month',
    // githubUrl intentionally omitted / undefined - do NOT invent a URL
    featured: false,
    badge: 'Full-Stack Web App',
    category: 'Full Stack & AI',
    role: 'Full Stack Developer',
    keyFeatures: [
      'Skill Tracking & Progress Scores from 0 to 100',
      'JWT Authentication & bcrypt Password Hashing',
      'Personal Dashboards & Complete Skill CRUD Operations',
      'Leaderboard & Advanced MongoDB Aggregation Queries',
      'Role-Based Access Control & Dedicated Admin Dashboard',
      'Protected Frontend Routes & Backend Authentication Middleware',
      'Axios API Communication & Routes → Controllers → Models Architecture',
      'MongoDB Database Management with Mongoose',
    ],
    highlights: [
      'Architected Express.js REST API with clean Routes → Controllers → Models separation and Mongoose schemas.',
      'Utilized MongoDB Aggregation pipelines to construct competitive leaderboards and analytical progress breakdowns.',
      'Secured backend endpoints with custom JWT authentication middleware and password encryption via bcrypt.',
    ],
  },
];
